stages:
  - lint
  - deploy

build:
  stage: lint
  image: registry.tsks.me/deploy/docker/base:master
  tags:
    - docker
  only:
    refs:
      - dev
      - master
      - main
  script:
    - npm i
    - gulp prod
    - ls -al
  artifacts:
    paths:
      - dist

deploy_dev:
  stage: deploy
  before_script:
    - apk update
    - apk add --no-cache lftp
  tags:
    - docker
  only:
    refs:
      - dev
  script:
    - lftp --version
    - lftp -e "open $FTP_HOST_DEV; user $FTP_USER_DEV $FTP_PASS_DEV; set ftp:ssl-allow no; mirror -X .* -X .*/ --reverse --verbose --delete ./ public_html/wp-content/themes/starter2/; bye"

deploy_master:
  stage: deploy
  before_script:
    - apk update
    - apk add --no-cache lftp
  tags:
    - docker
  only:
    refs:
      - master
      - main
  script:
    - lftp --version
    - lftp -e "open $FTP_HOST; user $FTP_USER $FTP_PASS; set ftp:ssl-allow no; mirror -X .* -X .*/ --reverse --verbose --delete ./ public_html/wp-content/themes/starter2/; bye"

